import Head from 'next/head'
import { useRouter } from 'next/router'
import ClimaComponent from "../../components/climaComponent";
import ListComponent from "../../components/listComponent";
import Footer from '../../components/footer'
import BackBtn from '../../components/backBtn';

export default function Templado() {
    const router = useRouter()
    const ruta = router.query
    const tiempo = router.asPath.split('/')
    const climaa = tiempo[1]
    return (
        <>
            <Head>
                <title>Comemos en {ruta.id}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/cocina.ico" />
            </Head>
            <div>
                <ClimaComponent />
                <BackBtn />
                <ListComponent climaa={climaa} />
                <Footer />
            </div>
        </>
    )
}